<a href="https://colab.research.google.com/github/VORVALK/pytorch_fundamentals/blob/main/pytorch_fundamentals_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource motebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
## Import libraries

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cu121


## Introduction to tensors
### Creating tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar
scalar.ndim

0

In [3]:
# Get tensor back as Python int
scalar.item()

7

In [4]:
# Create a vector
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [5]:
# Create a matrix
mtx = torch.tensor([[7,8],[9,10]])
mtx
mtx.shape

torch.Size([2, 2])

In [6]:
# Create tensor
TNS = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TNS.shape
# tensor shape is 1 x 3 x 3

torch.Size([1, 3, 3])

### Random Tensors

In [7]:
random_tensor = torch.rand(4,5)
random_tensor

random_image_tensor = torch.rand(256,256,3)
random_image_tensor

tensor([[[0.4326, 0.9379, 0.9708],
         [0.0239, 0.5548, 0.8697],
         [0.5281, 0.4685, 0.8697],
         ...,
         [0.2720, 0.4139, 0.7671],
         [0.4537, 0.3114, 0.2026],
         [0.8026, 0.1007, 0.6473]],

        [[0.4630, 0.1046, 0.6737],
         [0.7056, 0.6229, 0.6219],
         [0.6809, 0.3122, 0.4384],
         ...,
         [0.4210, 0.0621, 0.5429],
         [0.8797, 0.4154, 0.3765],
         [0.7598, 0.5726, 0.6234]],

        [[0.5198, 0.8008, 0.9242],
         [0.5888, 0.3950, 0.8864],
         [0.1003, 0.4451, 0.4198],
         ...,
         [0.5505, 0.6864, 0.2431],
         [0.6490, 0.7854, 0.0661],
         [0.2312, 0.9722, 0.7723]],

        ...,

        [[0.5926, 0.6678, 0.9719],
         [0.6417, 0.0963, 0.0140],
         [0.8704, 0.4107, 0.1047],
         ...,
         [0.3458, 0.4883, 0.2670],
         [0.2410, 0.7081, 0.4411],
         [0.0398, 0.5392, 0.8981]],

        [[0.9559, 0.7882, 0.4189],
         [0.8812, 0.8943, 0.9701],
         [0.

### Create a tensor of all zeros

In [8]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Create a tensor of all ones

In [9]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Create a range of tenors and tensors-like

In [10]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
rand_tensor = torch.arange(start=0, end=1000, step=77)
rand_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [12]:
# Converting tensor to all zeros
ten_zeros = torch.zeros_like(rand_tensor)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [13]:
# Float32 Tensor
float32_tensor = torch.tensor([3.0,6.0, 9.0],
                              dtype=None,           # what data type is the tensor
                              device=None,          # what device is on (CPU vs GPU)
                              requires_grad=False)  # whether or not to track gradients with this tensor's operations
float32_tensor.dtype

torch.float32

In [14]:
# Float16 Tensor (convert from float32 tensor)
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [15]:
# Different datatypes can operate
dif_types=float16_tensor * float32_tensor

# Tensor details
print(dif_types)
print(f"Tenso datatype: {dif_types.dtype}")
print(f"Tensor shape: {dif_types.shape}")
print(f"Device tensor is on: {dif_types.device}")

tensor([ 9., 36., 81.])
Tenso datatype: torch.float32
Tensor shape: torch.Size([3])
Device tensor is on: cpu


## Tensor operations

In [16]:
# Tensor addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [17]:
# Tensor multiply
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [18]:
# Tensor subtract
tensor - 10

tensor([ 0, 10, 20])

In [19]:
# PyTorch in-built functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([100, 200, 300])
tensor([20, 30, 40])


## Matrix multiplication

In [22]:
print(tensor)
torch.matmul(tensor, tensor)

## same as:
val = 0
for i in range(len(tensor)):
  val += tensor[i]*tensor[i]
print(val)


tensor([10, 20, 30])
tensor(1400)


In [25]:
# Matrix dimensions in multiplication -> inner dimension must be equal. outter dimension is final matrix dimension
print(torch.matmul(torch.rand(3,2), torch.rand(2,3)))
print(torch.matmul(torch.rand(2,3), torch.rand(3,2)))
# print(torch.matmul(torch.rand(3,2), torch.rand(3,2))) -> won't work (inner dimensions don't match)

tensor([[0.6732, 0.7192, 0.1045],
        [0.3678, 0.4647, 0.1262],
        [0.9875, 1.1586, 0.2531]])
tensor([[0.7212, 0.5091],
        [0.4826, 0.5187]])


In [28]:
# Manipulate tensor dimensions with transpose
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

print(tensor_B.T)
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 7,  8,  9],
        [10, 11, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])