<a href="https://colab.research.google.com/github/VORVALK/pytorch_fundamentals/blob/main/pytorch_fundamentals_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource motebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
## Import libraries

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


## Introduction to tensors
### Creating tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Create a vector
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [6]:
# Create a matrix
mtx = torch.tensor([[7,8],[9,10]])
mtx
mtx.shape

torch.Size([2, 2])

In [7]:
# Create tensor
TNS = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TNS.shape
# tensor shape is 1 x 3 x 3

torch.Size([1, 3, 3])

### Random Tensors

In [8]:
random_tensor = torch.rand(4,5)
random_tensor

random_image_tensor = torch.rand(256,256,3)
random_image_tensor

tensor([[[0.9171, 0.2376, 0.0245],
         [0.5872, 0.4410, 0.0252],
         [0.2019, 0.7269, 0.4760],
         ...,
         [0.3919, 0.8085, 0.8975],
         [0.1836, 0.6159, 0.6980],
         [0.8624, 0.9465, 0.1092]],

        [[0.0061, 0.9930, 0.7358],
         [0.0885, 0.0224, 0.8937],
         [0.7213, 0.5220, 0.5478],
         ...,
         [0.9208, 0.8246, 0.7915],
         [0.2643, 0.9671, 0.7229],
         [0.7482, 0.9422, 0.1817]],

        [[0.2413, 0.8458, 0.9654],
         [0.5275, 0.9623, 0.0853],
         [0.0307, 0.5961, 0.3759],
         ...,
         [0.8461, 0.9226, 0.4272],
         [0.7744, 0.0840, 0.8050],
         [0.0517, 0.8633, 0.2926]],

        ...,

        [[0.6077, 0.4688, 0.8592],
         [0.3204, 0.1059, 0.1489],
         [0.0290, 0.4601, 0.3300],
         ...,
         [0.1979, 0.0572, 0.8122],
         [0.8908, 0.0037, 0.4898],
         [0.9502, 0.1059, 0.8910]],

        [[0.8508, 0.9379, 0.1799],
         [0.2528, 0.8007, 0.3855],
         [0.

### Create a tensor of all zeros

In [9]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Create a tensor of all ones

In [10]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Create a range of tenors and tensors-like

In [11]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
rand_tensor = torch.arange(start=0, end=1000, step=77)
rand_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [13]:
# Converting tensor to all zeros
ten_zeros = torch.zeros_like(rand_tensor)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [16]:
# Float32 Tensor
float32_tensor = torch.tensor([3.0,6.0, 9.0],
                              dtype=None,           # what data type is the tensor
                              device=None,          # what device is on (CPU vs GPU)
                              requires_grad=False)  # whether or not to track gradients with this tensor's operations
float32_tensor.dtype

torch.float32

In [18]:
# Float16 Tensor (convert from float32 tensor)
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
# Different datatypes can operate
dif_types=float16_tensor * float32_tensor

# Tensor details
print(dif_types)
print(f"Tenso datatype: {dif_types.dtype}")
print(f"Tensor shape: {dif_types.shape}")
print(f"Device tensor is on: {dif_types.device}")

tensor([ 9., 36., 81.])
Tenso datatype: torch.float32
Tensor shape: torch.Size([3])
Device tensor is on: cpu
